Fixed Code execution in swig
418sec/swig pull request #1
Opened 2020-09-10 09:51 UTC by alromh87

### 📊 Metadata *

_Please enter the direct URL for this bounty on huntr.dev. This is compulsory and will help us process your bounty submission quicker._

#### Bounty URL:

### ⚙️ Description *

_Describe your fix clearly and concisely - imagine you are describing it to a non-technical friend._

### 💻 Technical Description *

_Describe in-depth, the technical implementation of the proposed security fix. Imagine you are describing it to a NASA engineer._

### 🐛 Proof of Concept (PoC) *

_Provide the vulnerability exploit to show the security issue you're fixing._

### 🔥 Proof of Fix (PoF) *

_Replay the vulnerability exploit to show the successful fix and mitigation of the vulnerability._

### 👍 User Acceptance Testing (UAT)

_Run a unit test or a legitimate use case to prove that your fix does not introduce breaking changes._

2020-09-10 11:49 UTC, Mik317 requested changes
The `fix` is bypassable since `|` isn't checked 😢 

PoC: 
![image](https://user-images.githubusercontent.com/33063403/92725452-78fbb200-f36c-11ea-90cd-455f62794b36.png)

Cheers,
Mik

2020-09-10 15:11 UTC, alromh87 commented
Thanks Mik I updated for best performance  in python

2020-09-10 15:23 UTC, Mik317 requested changes
Still bypassable using `backticks` :

![image](https://user-images.githubusercontent.com/33063403/92753599-524c7400-f38a-11ea-9cc7-98ca4c29789b.png)

Cheers,
Mik

2020-09-10 15:42 UTC, alromh87 commented
Thanks

2020-09-10 21:42 UTC, Mik317 requested changes
Hi @alromh87 :smile:,
thanks for the `minor fix` :+1: 
I identified another small `bypass` which makes possible `RCE` (more info on how resolve in the comment):

![Screenshot from 2020-09-10 23-39-35](https://user-images.githubusercontent.com/33063403/92811960-3b744480-f3bf-11ea-93e4-e040eb6e1408.png)

Cheers,
Mik

2020-09-10 21:42 UTC, Mik317 commented on Tools/mkdist.py
> +    return arg.replace('`','').replace('\'','').replace('"','').replace(';','').replace('&','').replace(',','').replace('\\','').replace('|','')
Clean also `${}` and `$()` since could result in `RCE`

2020-09-11 08:51 UTC, alromh87 commented on Tools/mkdist.py
> +    return arg.replace('`','').replace('\'','').replace('"','').replace(';','').replace('&','').replace(',','').replace('\\','').replace('|','')
This is a tricky one, thanks for your help debbuging

2020-09-11 10:17 UTC, Mik317 requested changes
The fix is still bypassable using another syntax.
I added more info in the comment :smile:

Cheers,
Mik

2020-09-11 10:17 UTC, Mik317 commented on Tools/mkdist.py
> +    return arg.replace('`','').replace('\'','').replace('"','').replace(';','').replace('&','').replace(',','').replace('\\','').replace('|','').replace('$','')
Still bypassable :cry: 
The `(command)` format is possible in `Windows`, leading to `RCE` again

2020-09-11 20:27 UTC, alromh87 commented
Implemented a cleaner fix

https://github.com/418sec/swig/pull/2

2020-09-11 20:27 UTC, closed without merging